services:
  web:
    image: nginx:latest
    container_name: imobis_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/php8-fpm/Dockerfile
    container_name: imobis_php
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  db:
    image: mysql:8.0
    container_name: imobis_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imobis
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: